---

- name: Jetty - install package
  include_tasks: "install.yml"
  when: jetty_install

- name: Jetty - configure application server
  include_tasks: "configure.yml"
  when: jetty_modules_configure

- name: Jetty - generate self-signed certificate
  include_tasks: "ssl.yml"
  when: jetty_ssl_generate_cert

- name: Jetty - update `systemd` configuration
  include_tasks: "systemd.yml"
  when: jetty_service_enabled
